In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy

print(numpy.__version__)

2.3.5


In [3]:
#alice

import numpy as np

print(np.__version__)

2.3.5


In [4]:
#1d

arr = np.array([10,20,30])

print("one dimensional array :",arr)

one dimensional array : [10 20 30]


In [33]:
#2d

arr2d = np.array([[10,20,30],[40.0,50,60]])

print("two dimensional array : \n",arr2d)

two dimensional array : 
 [[10. 20. 30.]
 [40. 50. 60.]]


#  type

In [6]:
print("Type : ",type(arr))

Type :  <class 'numpy.ndarray'>


In [22]:
print("Type : ",type(arr2d))

Type :  <class 'numpy.ndarray'>


# shape

In [8]:
print(arr.shape)

(3,)


In [9]:
print(arr2d.shape)

(2, 3)


#   size

In [23]:
print(arr.size)
print(arr2d.size)

3
6


#  find dimensional

In [30]:
print("dimensional array? : ",arr.ndim)
print("dimensional array? : ",arr2d.ndim)

dimensional array? :  1
dimensional array? :  2


#   Data type


In [39]:
print(arr.dtype)
print(arr2d.dtype)
print(arr2d)

int64
int64
[[10 20 30]
 [40 50 60]]


In [38]:
arr2d = np.array([[10,20,30],[40.0,50,60]],dtype = int)   #explicit

print(arr2d.dtype)
print(arr2d)

int64
[[10 20 30]
 [40 50 60]]


#  zeros

In [49]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [52]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [55]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [57]:
print(np.empty((2,3)))

[[3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]]
