In [108]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [109]:
import numpy as np

In [110]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [111]:
print(np.__version__)

2.3.5


In [112]:
arr = np.array([1,2,3,4,5])

print(arr)
print("\n")
print(type(arr))

[1 2 3 4 5]


<class 'numpy.ndarray'>


In [113]:
arr = np.array((1,2,3,4,5))

print(arr)
print("\n")
print(type(arr))

[1 2 3 4 5]


<class 'numpy.ndarray'>


# 0D array



In [114]:
arr = np.array(43)
print(arr)

43


# 1D array

In [115]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


# 2D array

In [116]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 3D array

In [117]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4D array

In [118]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Check Number of Dimensions

attribute - ndim

In [119]:
arr1 = np.array(43)
arr2 = np.array([1,2,3])
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr4 = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr5 = np.array([[1,2],[3,4],[5,6],[7,8]])


print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)

0
1
2
2
2


# Higher Dimensional Arrays

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [120]:
arr = np.array([1],ndmin=3)

print(arr)

[[[1]]]


# NumPy Array Indexing

Access Array Elements

In [121]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[0])

1


In [122]:
arr = np.array([1, 2, 3, 4])

print(arr[2])

3


In [123]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


### 2D array

In [124]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1,2])

8


In [125]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


print(arr[0][4])

5


###  3D array 

In [126]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1][1][1])

11


#  Negative Indexing

In [127]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1][-1])

10


In [128]:
print(arr[-2][2])

3


In [129]:
print(arr[-1][2])

8


# NumPy Array Slicing

###  Slicing arrays

In [130]:
import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[0:5])

[1 2 3 4 5]


In [131]:
print(arr[4:])

[5 6 7 8 9]


In [132]:
print(arr[:3])

[1 2 3]


### Negative Slicing

In [133]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-4:-2])

[4 5]


In [134]:
print(arr[-4:-1])

[4 5 6]


In [135]:
print(arr[-1:])

[7]


In [136]:
print(arr[:-1])

[1 2 3 4 5 6]


###   STEP

In [137]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [138]:
print(arr[0:5:2])

[1 3 5]


In [139]:
print(arr[0:6:2])

[1 3 5]


In [140]:
print(arr[-5:-1:3])

[3 6]


In [141]:
print(arr[1:4:2])

[2 4]


### Slicing 2-D Arrays

In [142]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1,0:3])

[6 7 8]


In [143]:
print(arr[0:3,4])

[ 5 10]


In [144]:
print(arr[0:3,1:4])

[[2 3 4]
 [7 8 9]]


#   NumPy Data Types

### Data Types in Python

                    strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
                    integer - used to represent integer numbers. e.g. -1, -2, -3
                    float - used to represent real numbers. e.g. 1.2, 42.42
                    boolean - used to represent True or False.
                    complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

     Data Types in NumPy
     NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

     Below is a list of all data types in NumPy and the characters used to represent them.

        i - integer
        b - boolean
        u - unsigned integer
        f - float
        c - complex float
        m - timedelta
        M - datetime
        O - object
        S - string
        U - unicode string
        V - fixed chunk of memory for other type ( void )


In [145]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print(arr.dtype)

int64


In [146]:
arr = np.array(["apple","orange","banana"])

print(arr.dtype)

<U6


In [147]:
arr = np.array([1,2,3,4,5,6],dtype = 'S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [148]:
arr = np.array([1,2,3,4,5,6],dtype = 'f')

print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
float32


In [149]:
arr = np.array([1,2,3,4,5],dtype = 'i4')

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


Astype

In [150]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

narr = arr.astype('i')
print(narr.dtype)
print(arr.dtype)

int32
int64


In [151]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

narr = arr.astype(int)
print(narr.dtype)
print(arr.dtype)

int64
int64


In [152]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

narr = arr.astype(bool)
print(narr.dtype)
print(narr)

bool
[ True  True  True  True  True  True]


#  NumPy Array Copy vs View

In [160]:
arr = np.array([1,2,3,4,5])
                                             #copy is a new array
x= arr.copy()                                #The copy owns the data and any changes made to the copy will not affect original array
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [161]:
arr = np.array([1,2,3,4,5])                  #view is just a view of the original array

y = arr.view()                              #The view does not own the data and any changes made to the view will affect the original array
arr[0] = 12

print(arr)
print(y)

[12  2  3  4  5]
[12  2  3  4  5]


In [163]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 32

print(arr)
print(x)

[32  2  3  4  5]
[32  2  3  4  5]


# Check if Array Owns its Data

In [164]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# NumPy Array Shape

attribute - shape

In [168]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print('shape of array :',arr.shape)

shape of array : (2, 4)


# NumPy Array Reshaping

In [176]:
arr = np.array([1,2,3,4,5,6,7,8,9,1])

new_array = arr.reshape(5,2)

print(new_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]]


In [180]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [181]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# numpy array iteration

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [7]:
arr = np.array([[1, 2, 3, 4, 5],[7, 8, 9, 10, 11]])

for i in arr:
    print(i)

[1 2 3 4 5]
[ 7  8  9 10 11]


In [8]:
arr = np.array([[1, 2, 3, 4, 5],[7, 8, 9, 10, 11]])

for i in arr:
    for j in arr:
        print(j)

[1 2 3 4 5]
[ 7  8  9 10 11]
[1 2 3 4 5]
[ 7  8  9 10 11]


In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


for i in arr:
    for j in arr:
        for k in (arr):
            print(k)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [12]:
arr = np.array([[1, 2, 3, 4, 5],[7, 8, 9, 10, 11]])

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
7
8
9
10
11


In [13]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


#### ndenumerate

In [15]:
arr = np.array([[1, 2, 3, 4, 5],[7, 8, 9, 10, 11]])

for ndx,i in np.ndenumerate(arr):
    print(ndx,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 7
(1, 1) 8
(1, 2) 9
(1, 3) 10
(1, 4) 11


# Joining NumPy Arrays

In [16]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [21]:
arr1 = np.array([[1, 2,],[ 3,4]])

arr2 = np.array([[4, 5,],[ 6,7]])

arr = np.concatenate((arr1, arr2),axis = 1)         #axis = 1

print(arr)

[[1 2 4 5]
 [3 4 6 7]]


# Joining Arrays Using Stack Functions

#### stack

In [22]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.stack((arr1,arr2),axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


####  hstack

In [25]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.hstack((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


#### vstack

In [26]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.vstack((arr1,arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


#### dstack

In [27]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.dstack((arr1,arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array

### Splitting NumPy Arrays

In [30]:
arr = np.array([1,2,3,4,5,6])

new_arr = np.array_split(arr,3)

print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5 6]


In [42]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [46]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12],[13,14],[15,16]])

new_arr = np.array_split(arr,4)

print(new_arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]]), array([[13, 14],
       [15, 16]])]


#### hsplit

In [47]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


#  NumPy Searching Arrays

### Searching Arrays

In [54]:
arr = np.array([1,2,3,4,5])             #output will show the index of the given number

x = np.where(arr==4)

print(x)

(array([3]),)


In [55]:
arr = np.array([1,2,3,4,5,4,4,4])

x = np.where(arr==4)

print(x)

(array([3, 5, 6, 7]),)


In [56]:
import numpy as np

arr = np.array([10, 14, 93, 41, 8, 7])

x = np.where(arr%2 == 1)

print(x)

(array([2, 3, 5]),)


In [58]:
arr = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


####  Search Sorted

In [59]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


#### Search From the Right Side

In [60]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


#### Multiple Values

In [61]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
