In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [7]:
print(np.__version__)

2.3.5


In [10]:
arr = np.array([1,2,3,4,5])

print(arr)
print("\n")
print(type(arr))

[1 2 3 4 5]


<class 'numpy.ndarray'>


In [11]:
arr = np.array((1,2,3,4,5))

print(arr)
print("\n")
print(type(arr))

[1 2 3 4 5]


<class 'numpy.ndarray'>


# 0D array



In [14]:
arr = np.array(43)
print(arr)

43


# 1D array

In [15]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


# 2D array

In [20]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 3D array

In [22]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4D array

In [25]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Check Number of Dimensions

attribute - ndim

In [28]:
arr1 = np.array(43)
arr2 = np.array([1,2,3])
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr4 = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr5 = np.array([[1,2],[3,4],[5,6],[7,8]])


print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)

0
1
2
2
2


# Higher Dimensional Arrays

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [33]:
arr = np.array([1],ndmin=3)

print(arr)

[[[1]]]


# NumPy Array Indexing

Access Array Elements

In [34]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[0])

1


In [35]:
arr = np.array([1, 2, 3, 4])

print(arr[2])

3


In [36]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7
